### PR TITLE
Update arch packaging

### PR DESCRIPTION
**Pull request by chrisroberts**
Build substrate-less packages for Arch

### CODE REVIEW

**Comment by jsteel44** [comment]
@chrisroberts thanks! However I just built the package with your PKGBUILD and I get:

```
$ vagrant --version
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: no such file or directory
```

Looks like it's still expecting the substrate binaries to be there.

**Comment by chrisroberts** [comment]
@jsteel44 Needs to use the env var to not pull the installers from master:

```
$ VAGRANT_INSTALLERS_VERSION=e-arch makepkg ...
```

**Comment by jsteel44** [comment]
@chrisroberts just tried that but have the same issue I'm afraid.

**Comment by chrisroberts** [comment]
@jsteel44 Are you sure you have the env var set? If you end up with the launcher looking for the embedded Ruby it means that master is being pulled from vagrant installers. The `e-arch` branch (this PR) has updates to the launcher. Perhaps the original source assets need to be deleted from the first run?

**Comment by jsteel44** [comment]
@chrisroberts I just deleted my build directory and rebuilt but still no luck:
```
$ rm -rf *.pkg.tar.xz pkg src
$ VAGRANT_INSTALLERS_VERSION=e-arch makepkg
$ pacman -U hashicorp-vagrant-2.0.0-1-x86_64.pkg.tar.xz
$ vagrant --version
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: no such file or directory
```
What do you think I might be missing?

**Comment by jsteel44** [comment]
@chrisroberts ah, I changed the source for vagrant-installers to be the latest in git rather than the archive tarball of the branch and that seems to work! Maybe the tarball was out of date (or only updated periodically). Thanks for getting this sorted, I'll let you know how I get on, cheers.

**Comment by jsteel44** [comment]
@chrisroberts I'm getting some warnings when running vagrant commands (vagrant status for eg):

```
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
Ignoring wdm-0.1.1 because its extensions are not built.  Try: gem pristine wdm --version 0.1.1
/opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/cli.rb:48: warning: constant ::Fixnum is deprecated
```

**Comment by jsteel44** [comment]
@chrisroberts ah, using ruby 2.4 (against vagrant git) seems to resolve those issues but I can't build vagrant 2.0.0 with ruby 2.4, only 2.3. I guess there are some changes in git that I'll need to wait for to hit the next release. Thanks again

**Pull request merged**
